2025-03-17 16:14:47,675 INFO    Thread-3 (_run_job):18500 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-17 16:14:47,675 INFO    Thread-3 (_run_job):18500 [wandb_setup.py:_flush():67] Configure stats pid to 18500
2025-03-17 16:14:47,675 INFO    Thread-3 (_run_job):18500 [wandb_setup.py:_flush():67] Loading settings from C:\Users\ANJALI VERMA\.config\wandb\settings
2025-03-17 16:14:47,675 INFO    Thread-3 (_run_job):18500 [wandb_setup.py:_flush():67] Loading settings from K:\DA6401\da6401_assignment1\wandb\settings
2025-03-17 16:14:47,675 INFO    Thread-3 (_run_job):18500 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-17 16:14:47,675 INFO    Thread-3 (_run_job):18500 [wandb_init.py:setup_run_log_directory():647] Logging user logs to K:\DA6401\da6401_assignment1\wandb\run-20250317_161447-xzhwe4ew\logs\debug.log
2025-03-17 16:14:47,676 INFO    Thread-3 (_run_job):18500 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to K:\DA6401\da6401_assignment1\wandb\run-20250317_161447-xzhwe4ew\logs\debug-internal.log
2025-03-17 16:14:47,676 INFO    Thread-3 (_run_job):18500 [wandb_init.py:init():761] calling init triggers
2025-03-17 16:14:47,676 INFO    Thread-3 (_run_job):18500 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 16, 'beta': 0.9, 'beta1': 0.9, 'beta2': 0.999, 'dataset': 'fashion_mnist', 'epochs': 20, 'epsilon': 1e-08, 'hidden_size': 32, 'learning_rate': 0.001, 'loss': 'cross_entropy', 'momentum': 0.9, 'num_layers': 3, 'optimizer': 'adam', 'weight_decay': 0.0005, 'weight_init': 'Xavier'}
config: {'_wandb': {}}
2025-03-17 16:14:47,676 INFO    Thread-3 (_run_job):18500 [wandb_init.py:init():784] starting backend
2025-03-17 16:14:47,676 INFO    Thread-3 (_run_job):18500 [wandb_init.py:init():788] sending inform_init request
2025-03-17 16:14:47,690 INFO    Thread-3 (_run_job):18500 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-03-17 16:14:47,690 INFO    Thread-3 (_run_job):18500 [wandb_init.py:init():798] backend started and connected
2025-03-17 16:14:47,692 INFO    Thread-3 (_run_job):18500 [wandb_run.py:_config_callback():1261] config_cb None None {'activation': 'tanh', 'batch_size': 16, 'beta': 0.9, 'beta1': 0.9, 'beta2': 0.999, 'dataset': 'fashion_mnist', 'epochs': 20, 'epsilon': 1e-08, 'hidden_size': 32, 'learning_rate': 0.001, 'loss': 'cross_entropy', 'momentum': 0.9, 'num_layers': 3, 'optimizer': 'adam', 'weight_decay': 0.0005, 'weight_init': 'Xavier'}
2025-03-17 16:14:47,693 INFO    Thread-3 (_run_job):18500 [wandb_init.py:init():891] updated telemetry
2025-03-17 16:14:47,695 INFO    Thread-3 (_run_job):18500 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-17 16:14:48,224 INFO    Thread-3 (_run_job):18500 [wandb_init.py:init():990] starting run threads in backend
2025-03-17 16:14:48,520 INFO    Thread-3 (_run_job):18500 [wandb_run.py:_console_start():2375] atexit reg
2025-03-17 16:14:48,522 INFO    Thread-3 (_run_job):18500 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-17 16:14:48,522 INFO    Thread-3 (_run_job):18500 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-17 16:14:48,522 INFO    Thread-3 (_run_job):18500 [wandb_run.py:_redirect():2315] Redirects installed.
2025-03-17 16:14:48,530 INFO    Thread-3 (_run_job):18500 [wandb_init.py:init():1032] run started, returning control to user process
2025-03-17 16:14:53,352 WARNING MsgRouterThr:18500 [router.py:message_loop():63] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\ANJALI VERMA\anaconda3\envs\dl\lib\site-packages\wandb\sdk\lib\sock_client.py", line 208, in _read_packet_bytes
    data = self._sock.recv(self._bufsize)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ANJALI VERMA\anaconda3\envs\dl\lib\site-packages\wandb\sdk\interface\router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
  File "C:\Users\ANJALI VERMA\anaconda3\envs\dl\lib\site-packages\wandb\sdk\lib\sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "C:\Users\ANJALI VERMA\anaconda3\envs\dl\lib\site-packages\wandb\sdk\lib\sock_client.py", line 212, in _read_packet_bytes
    raise SockClientClosedError from e
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ANJALI VERMA\anaconda3\envs\dl\lib\site-packages\wandb\sdk\interface\router.py", line 56, in message_loop
    msg = self._read_message()
  File "C:\Users\ANJALI VERMA\anaconda3\envs\dl\lib\site-packages\wandb\sdk\interface\router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-17 16:14:53,374 INFO    MsgRouterThr:18500 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
