2025-03-07 22:06:02,242 INFO    MainThread:9660 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-07 22:06:02,242 INFO    MainThread:9660 [wandb_setup.py:_flush():67] Configure stats pid to 9660
2025-03-07 22:06:02,242 INFO    MainThread:9660 [wandb_setup.py:_flush():67] Loading settings from C:\Users\ANJALI VERMA\.config\wandb\settings
2025-03-07 22:06:02,242 INFO    MainThread:9660 [wandb_setup.py:_flush():67] Loading settings from K:\DA6401\da6401_assignment1\wandb\settings
2025-03-07 22:06:02,243 INFO    MainThread:9660 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-07 22:06:02,243 INFO    MainThread:9660 [wandb_init.py:setup_run_log_directory():647] Logging user logs to K:\DA6401\da6401_assignment1\wandb\run-20250307_220602-vm644nhl\logs\debug.log
2025-03-07 22:06:02,245 INFO    MainThread:9660 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to K:\DA6401\da6401_assignment1\wandb\run-20250307_220602-vm644nhl\logs\debug-internal.log
2025-03-07 22:06:02,245 INFO    MainThread:9660 [wandb_init.py:init():761] calling init triggers
2025-03-07 22:06:02,245 INFO    MainThread:9660 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'wandb_project': 'da6401_a1', 'wandb_entity': 'da24m002-indian-institute-of-technology-madras', 'dataset': 'fashion_mnist', 'epochs': 20, 'batch_size': 64, 'loss': 'cross_entropy', 'optimizer': 'sgd', 'learning_rate': 0.1, 'momentum': 0.9, 'beta': 0.9, 'beta1': 0.9, 'beta2': 0.999, 'epsilon': 1e-08, 'weight_decay': 0.0, 'weight_init': 'Xavier', 'num_layers': 3, 'hidden_size': 128, 'activation': 'ReLU', '_wandb': {}}
2025-03-07 22:06:02,246 INFO    MainThread:9660 [wandb_init.py:init():784] starting backend
2025-03-07 22:06:02,246 INFO    MainThread:9660 [wandb_init.py:init():788] sending inform_init request
2025-03-07 22:06:02,262 INFO    MainThread:9660 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-07 22:06:02,263 INFO    MainThread:9660 [wandb_init.py:init():803] backend started and connected
2025-03-07 22:06:02,265 INFO    MainThread:9660 [wandb_init.py:init():896] updated telemetry
2025-03-07 22:06:02,265 INFO    MainThread:9660 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-07 22:06:02,887 INFO    MainThread:9660 [wandb_init.py:init():995] starting run threads in backend
2025-03-07 22:06:03,181 INFO    MainThread:9660 [wandb_run.py:_console_start():2377] atexit reg
2025-03-07 22:06:03,182 INFO    MainThread:9660 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-07 22:06:03,183 INFO    MainThread:9660 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-07 22:06:03,183 INFO    MainThread:9660 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-07 22:06:03,190 INFO    MainThread:9660 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-07 22:07:13,380 WARNING MsgRouterThr:9660 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\ANJALI VERMA\anaconda3\envs\dl\lib\site-packages\wandb\sdk\interface\router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "C:\Users\ANJALI VERMA\anaconda3\envs\dl\lib\site-packages\wandb\sdk\lib\sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "C:\Users\ANJALI VERMA\anaconda3\envs\dl\lib\site-packages\wandb\sdk\lib\sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ANJALI VERMA\anaconda3\envs\dl\lib\site-packages\wandb\sdk\interface\router.py", line 70, in message_loop
    msg = self._read_message()
  File "C:\Users\ANJALI VERMA\anaconda3\envs\dl\lib\site-packages\wandb\sdk\interface\router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-07 22:07:13,386 INFO    MsgRouterThr:9660 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
